server:
  port: 8084

spring:
  application:
    name: material-service
  datasource:
    url: jdbc:postgresql://postgres:5432/svdb
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/print-sv

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.materialservice: DEBUG
    liquibase: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
